export enum RolesEnum {
  ADMINISTRADOR = 'ADMINISTRADOR',
  GERENTE_INVENTARIO = 'GERENTE INVENTARIO',
  ENCARGADO_ALMACEN = 'ENCARGADO ALMACEN',
  OPERADOR_TECNICO = 'OPERADOR TECNICO',
  COMPRAS = 'COMPRAS',
  AUDITOR = 'AUDITOR',
}
